@schools = [
"Kettering University",
"Stanford University",
"Georgetown University",
"MIT",
"Harvard University",
"Princeton University",
"Yale University",
"Columbia University",
"University of Chicago",
"University of Pennsylvania",
"Duke University",
"Dartmouth College",
"Northwestern University",
"Johns Hopkins University",
"Brown University",
"Cornell University",
"Rice University",
"Vanderbilt University",
"University of Notre Dame",
"Emory University",
"UC Berkeley",
"Carnegie Mellon University",
"USC",
"UCLA",
"University of Virginia",
"Wake Forest University",
"University of Michigan",
"Tufts University",
"University of North Carolina",
"Boston College",
"Brandeis University",
"College of William and Mary",
"NYU",
"University of Rochester",
"Georgia Institute of Technology",
"UC San Diego",
"UC Santa Barbara",
"Ohio State University",
"University of Florida",
"Arizona State University",
"University of Minnesota",
"University of Texas",
"University of Central Florida",
"Texas A & M",
"Pennsylvania State University",
"University of Illinois",
"University of Wisconsin",
"Florida State University",
"Purdue University",
"University of Washington",
"Indiana University",
"University of Arizona",
"Lehigh University"
]
